export {
  READONLY_PROPERTY_LOCALS,
  stringFromValue,
  stringValuesEqual,
  propertyEditRules,
  rangeClassLocals,
  searchSchemaProperties,
  statementValueFromInput,
  propertyAppliesToClass,
  canRemoveValue,
  canAddValue,
  groupStatementsByProperty,
  type PropertyEditRules,
  type PropertyValueGroup,
  type PropertySearchHit,
} from "@itmap/archimate-core";
