export {
  OE_BATCH_CHUNK_SIZE,
  oxClientKey,
  entityRef,
  createOpBuffer,
  pushEnsureEntity,
  pushStringStatement,
  pushBoolStatement,
  pushRefStatement,
  pushInstanceOf,
  pushExchangeManaged,
  applyBatchResults,
  shouldFlush,
  type OpBuffer,
} from "@itmap/archimate-core";
